from .nodes.asr_nodes import NODE_CLASS_MAPPINGS as ASR_NODE_CLASS_MAPPINGS
from .nodes.asr_nodes import (
    NODE_DISPLAY_NAME_MAPPINGS as ASR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.media_nodes import NODE_CLASS_MAPPINGS as MEDIA_NODE_CLASS_MAPPINGS
from .nodes.media_nodes import (
    NODE_DISPLAY_NAME_MAPPINGS as MEDIA_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **MEDIA_NODE_CLASS_MAPPINGS,
    **ASR_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MEDIA_NODE_DISPLAY_NAME_MAPPINGS,
    **ASR_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
